agent:
  use: agent
  deps:
    llm: llm
    tools:
      - read-file
      - shell

llm:
  use: openai
  config:
    model: gpt-5.5

read-file:
  use: read-file
  config:
    root: .

shell:
  use: shell
